modelPath: Mig29.stl

boxRight: wall_hangar.png
boxLeft: wall_hangar.png
boxTop: wall_hangar.png
boxBottom: floor_hangar.png
boxFront: gates_hangar.png
boxBack: wall_hangar.png

lightColor:
  - 1.0
  - 1.0
  - 0.0
lightIntensity: 1.2
lightPosition:
  - -100.0
  - 200.0
  - 150.0
resolution: 
  - 800
  - 600
cameraPosition:
  - 150.0
  - 300.0
  - 200.0
cameraFovY: 70.0
boxScale:
  - 500.0
  - 300.0
  - 500.0
modelColor:
  - 0.7
  - 0.7
  - 1.0